[server]
enableStaticServing = true

[theme]
primaryColor = "#1476ff"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#F0F2F6"
sidebarBackgroundColor = "#FFFFFF"
sidebarSecondaryBackgroundColor = "#F0F2F6"
sidebarTextColor = "#262730"
textColor = "#262730"
borderColor = "#E7E7E8"
showBorderAroundInputs = false
roundness = 0.85
font = "Inter"

[[theme.fontFaces]]
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
family = "Inter"
font-weight = "100 900"
